server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

javax:
  net:
    ssl:
      trustStore: /tmp/certs/rds-truststore.jks
      trustStorePassword: zootopia-admin

spring:
  jackson:
    time-zone: Asia/Seoul
  data:
    mongodb:
      # uri: mongodb://zootopia:zootopia-admin@zootopia-mongodb.cluster-c2f2jpwzzxst.ap-northeast-2.docdb.amazonaws.com:27017/heartpath?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      uri: mongodb://zootopia:zootopia-admin@zootopia-mongodb.cluster-c2f2jpwzzxst.ap-northeast-2.docdb.amazonaws.com:27017/heartpath?tls=true&tlsCAFile=/tmp/certs/rds-truststore.jks&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/heartpath
#    username: zootopia
#    password:
#    driver-class-name: org.h2.Driver

#         MySQL
      # url: jdbc:mysql://zootopia-mysql.c2f2jpwzzxst.ap-northeast-2.rds.amazonaws.com:3306/zootopia
      # username: admin
      # password: zootopia-admin
      # driver-class-name: com.mysql.cj.jdbc.Driver

  # ?? ?? ??
  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true


cloud:
  aws:
    s3:
      bucket: zootopia-s3
    credentials:
      access-key: AKIAT2IXRZPUG2OFXNRM
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: zootopiaD203!

#env:
#  USER_URL
