server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jackson:
    time-zone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
    datasource:
      # MySQL
      url: jdbc:mysql://zootopia-mysql.c2f2jpwzzxst.ap-northeast-2.rds.amazonaws.com:3306/zootopia
      username: admin
      password: ENC(Gvm4XgQFXVwb3fpfTmdSxnd88htlJ/zV)
      driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true


cloud:
  aws:
    s3:
      bucket: zootopia-s3
    credentials:
      access-key: ENC(QjAZdSmPEbtCqu5y+s89uIJns8S+fjbkTx1o2ptn9TY=)
      secret-key: ENC(HembcJ68NF7PAmofcbLEh6Y3Spe2kRAQL1J3RIz4RX6Vy3mVYqi3RUPUl3AbgPmXYdi9it0jpFQ=)

    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
